/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentacion;

import Entidad.clsEntidadEvento;
import Negocio.clsEvento;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Charlie
 */
public class frmBuscarEvento extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmBuscarEvento
     */
    ArrayList<clsEntidadEvento> listaEventos;
    clsEntidadEvento _objEvento;
    IFormulario frmFormulario;
    
    public frmBuscarEvento(IFormulario frmFormulario) {
        initComponents();
        cargarTabla("");
        this.frmFormulario = frmFormulario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEvento = new javax.swing.JTable();
        txtBusqueda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        tblEvento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "idEvento", "Titulo Evento", "Tipo", "Fecha Inicial", "Fecha Final"
            }
        ));
        tblEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEventoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEvento);
        if (tblEvento.getColumnModel().getColumnCount() > 0) {
            tblEvento.getColumnModel().getColumn(0).setMinWidth(0);
            tblEvento.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        txtBusqueda.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtBusquedaInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEventoMouseClicked
        seleccionarTabla();
    }//GEN-LAST:event_tblEventoMouseClicked
    
    public void seleccionarTabla(){
        int fila = tblEvento.getSelectedRow();
        if (fila==-1){
            JOptionPane.showMessageDialog(null, "Debes seleccionar una fila");
        }else{
            _objEvento = listaEventos.get(fila);

        }
    }
    
    public void cargarTabla(String busqueda){
        listaEventos = clsEvento.listarEventos(busqueda);
        DefaultTableModel dtm = (DefaultTableModel)tblEvento.getModel();
        FrmMaster.limpiarTabla(tblEvento);
        for(clsEntidadEvento objEvento : listaEventos){
            Object[] fila = new Object[5];
            fila[0] = objEvento.getIdEvento();
            fila[1] = objEvento.getTipo();
            fila[2] = objEvento.getTitulo();
            fila[3] = objEvento.getFechaInicio();
            fila[4] = objEvento.getFechaFinal();
            
            dtm.addRow(fila);
        }
        tblEvento.setModel(dtm);
    }
    
    private void txtBusquedaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtBusquedaInputMethodTextChanged

    }//GEN-LAST:event_txtBusquedaInputMethodTextChanged

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
        cargarTabla(txtBusqueda.getText());
    }//GEN-LAST:event_txtBusquedaKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(tblEvento.getSelectedRow()>=0){
          frmFormulario.seleccionarEvento(_objEvento);
            this.dispose();  
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione un Evento");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEvento;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
