/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentacion;

import Entidad.clsEntidadPersona;
import Negocio.clsPrograma;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Charlie
 */
public class frmBuscarPonente extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmBuscarPonente
     */
    ArrayList<clsEntidadPersona> listaPersonas;
    clsEntidadPersona _objPersona;
    IFormulario frmFormulario;
    int idEvento;
    
    public frmBuscarPonente(IFormulario frmFormulario,int idEvento) {
        initComponents();
        this.frmFormulario = frmFormulario;
        this.idEvento = idEvento;
        cargarTabla("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersona = new javax.swing.JTable();
        txtBusqueda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        tblPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "idPersona", "Nombres", "Apellidos", "Email"
            }
        ));
        tblPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPersonaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPersona);

        txtBusqueda.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtBusquedaInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPersonaMouseClicked
        seleccionarTabla();
    }//GEN-LAST:event_tblPersonaMouseClicked
    
    public void seleccionarTabla(){
        int fila = tblPersona.getSelectedRow();
        if (fila==-1){
            JOptionPane.showMessageDialog(null, "Debes seleccionar una fila");
        }else{
            _objPersona = listaPersonas.get(fila);
        }
    }
    
    private void txtBusquedaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtBusquedaInputMethodTextChanged

    }//GEN-LAST:event_txtBusquedaInputMethodTextChanged

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
        cargarTabla(txtBusqueda.getText());
    }//GEN-LAST:event_txtBusquedaKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(tblPersona.getSelectedRow()>=0){
            frmFormulario.seleccionarUsuario(_objPersona);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una Persona");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void cargarTabla(String busqueda){
        listaPersonas = clsPrograma.listarPonentesNoInscritos(busqueda,idEvento);
        DefaultTableModel dtm = (DefaultTableModel)tblPersona.getModel();
        FrmMaster.limpiarTabla(tblPersona);
        for(clsEntidadPersona objPersona : listaPersonas){
            Object[] fila = new Object[6];
            fila[0] = objPersona.getIdPersona();
            fila[1] = objPersona.getNombres();
            fila[2] = objPersona.getApellidos();
            fila[3] = objPersona.getEmail();
            
            dtm.addRow(fila);
        }
        tblPersona.setModel(dtm);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPersona;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
