/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentacion;

import Entidad.*;
import Negocio.*;
import static Presentacion.FrmConsultaEvento.rs;
import java.awt.Component;
import java.sql.*;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class FrmConsultarProgramaEvento extends javax.swing.JInternalFrame {

    ArrayList<clsEntidadEvento> listaEventos;  
    clsEntidadEvento _objEvento;
    
    static ResultSet rs = null;
    DefaultTableModel dtm = new DefaultTableModel();
    
    public FrmConsultarProgramaEvento(clsEntidadEvento ce) {
        String titulos[] = {"Nombre Ponente","Tema","Fecha Inicial","Fecha Final"};
        dtm.setColumnIdentifiers(titulos);
        _objEvento= ce;
        initComponents();
    }
    
     public void cargarTabla(String busqueda){
        listaEventos = clsEvento.listarEventos(busqueda);
        DefaultTableModel dtm = (DefaultTableModel)tblEvento.getModel();
        FrmMaster.limpiarTabla(tblEvento);
        for(clsEntidadEvento objEvento : listaEventos){
            Object[] fila = new Object[6];
            fila[0] = objEvento.getIdEvento();
            fila[1] = objEvento.getTipo();
            fila[2] = objEvento.getFechaInicio();
            fila[3] = objEvento.getFechaFinal();
            
            dtm.addRow(fila);
        }
        tblEvento.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEvento = new javax.swing.JTable();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Consultar Evento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 11, -1, -1));

        btnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/application_add.png"))); // NOI18N
        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 43, -1, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/remove.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 43, -1, -1));

        tblEvento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NombreCompleto", "Tema", "FechaInicio", "FechaFinal"
            }
        ));
        jScrollPane1.setViewportView(tblEvento);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 104, 672, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        clsEvento evento = new clsEvento();
    try{
        rs = evento.consultarProgramaEvento(_objEvento.getIdEvento());
        boolean encuentra = false;
        String Datos[] = new String[4];
        int f,i;
        f = dtm.getRowCount();
        if(f>0){
            for(i=0; i<f; i++){
                dtm.removeRow(0);
            }
        }
        
        while(rs.next()){
            Datos[0] = (String) rs.getString(1);
            Datos[1] = (String) rs.getString(2);
            Datos[2] = (String) rs.getString(3);
            Datos[3] = (String) rs.getString(4);
           
            dtm.addRow(Datos);
            encuentra = true;
        }
        if(encuentra = false){
            JOptionPane.showMessageDialog(null, "Registro no encontrado");
        }
    }catch(Exception ex){
        ex.printStackTrace();
    }
    tblEvento.setModel(dtm);
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEvento;
    // End of variables declaration//GEN-END:variables
}
