/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentacion;
import Entidad.*;
import Negocio.*;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BEPIS
 */
public class frmComision extends javax.swing.JInternalFrame implements IMantenimiento{
    ArrayList<clsEntidadComision> listaComision;  
    clsEntidadComision _objComision;
    boolean isNuevoActivo;
    static int intContador;
    String id[]=new String[100];

    /**
     * Creates new form frmComision
     */
    public frmComision() {
        initComponents();
        cargarTabla("");
        FrmMaster.BloquearControles(pnlForm);
        FrmMaster.BloquearBotones(pnlForm, "Cancelar");
    }

    
     @Override
    public void cargarTabla(String busqueda){
        listaComision = clsComision.listarComision(busqueda);
        DefaultTableModel dtm = (DefaultTableModel)tblComision.getModel();
        FrmMaster.limpiarTabla(tblComision);
        for(clsEntidadComision objComision : listaComision){
            Object[] fila = new Object[15];
            fila[0] = objComision.getIdPersona();
            fila[1] = objComision.getIdEvento();
            fila[2] = objComision.getTipo();


            dtm.addRow(fila);
        }
        tblComision.setModel(dtm);
    }
    
      @Override
    public void seleccionarTabla(){
        int fila = tblComision.getSelectedRow();
        if (fila==-1){
            JOptionPane.showMessageDialog(null, "Debes seleccionar una fila");
        }else{
            txtPersona.setText(String.valueOf(_objComision.getIdPersona()));
            txtEvento.setText(String.valueOf(_objComision.getIdEvento()));
            txtEvento.setText(String.valueOf(_objComision.getTipo()));
        }
    }
    
    @Override
    public void guardar(){
        clsEntidadComision objComision = new clsEntidadComision();
        objComision.setIdPersona(Integer.parseInt(txtPersona.getText()));
        objComision.setIdEvento(Integer.parseInt(txtEvento.getText()));
        objComision.setTipo(txtTipo.getText());
        clsComision.agregarComision(objComision);
        cargarTabla("");
    }
    
    @Override
    public void modificar() {
        clsEntidadComision objComision = new clsEntidadComision();
        objComision.setIdPersona(_objComision.getIdPersona());
        objComision.setIdEvento(_objComision.getIdEvento());
        objComision.setTipo(txtTipo.getText());
        clsComision.modificarComision(objComision);
        cargarTabla("");
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlForm = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPersona = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEvento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        pnlBotones = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblComision = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlForm.setBackground(new java.awt.Color(255, 255, 255));
        pnlForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("ID Persona:");
        pnlForm.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        pnlForm.add(txtPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 170, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("ID Evento:");
        pnlForm.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        pnlForm.add(txtEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 170, 30));

        jLabel2.setText("Tipo Comision:");
        pnlForm.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        pnlForm.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 170, 30));

        getContentPane().add(pnlForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 320, 150));

        pnlBotones.setBackground(new java.awt.Color(255, 255, 255));
        pnlBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevo.setBackground(new java.awt.Color(153, 255, 51));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        pnlBotones.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/record.png"))); // NOI18N
        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, -1));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/page_edit.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, -1));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/page_remove.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/computer_remove.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnlBotones.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 100, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/remove.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 100, -1));

        getContentPane().add(pnlBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 120, 250));

        tblComision.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "idPersona", "idEvento", "Tipo Comision"
            }
        ));
        tblComision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblComisionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblComision);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 490, 120));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Mantenimiento de Comision");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 11, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("F:\\ProyectoFinal_EventoV4\\Sistema_Eventos\\src\\img\\fondobriseida.png")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        isNuevoActivo=true;
        FrmMaster.HabilitarControles(pnlForm);
        FrmMaster.LimpiarCampos(pnlForm);
        FrmMaster.BloquearBotones(pnlBotones, "Nuevo");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed

        if(isNuevoActivo){
            guardar();
        }else{
            modificar();
        }
        FrmMaster.BloquearBotones(pnlBotones, "Guardar");
        FrmMaster.LimpiarCampos(pnlForm);
        FrmMaster.BloquearControles(pnlForm);
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        if(tblComision.getSelectedRow()>0){
            isNuevoActivo=false;
            FrmMaster.HabilitarControles(pnlForm);
            FrmMaster.BloquearBotones(pnlBotones, "Modificar");
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione un registro!");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        /*
        int r;
        r = JOptionPane.showConfirmDialog(null, "¿Estas seguro de Eliminar el registro?",
            "Pregunta",0);
        if(r==0){
            clsPonente oper = new clsPonente();
            oper.EliminarPonente(Codigo);
            actualizarTabla();
            limpiarCampos();

        }
        */
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        FrmMaster.BloquearBotones(pnlBotones, "Cancelar");
        FrmMaster.LimpiarCampos(pnlForm);
        FrmMaster.BloquearControles(pnlForm);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tblComisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblComisionMouseClicked
        seleccionarTabla();
    }//GEN-LAST:event_tblComisionMouseClicked

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JTable tblComision;
    private javax.swing.JTextField txtEvento;
    private javax.swing.JTextField txtPersona;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
