/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentacion;

import Entidad.*;
import Negocio.*;
import java.awt.Component;
import java.sql.*;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class FrmConsultaComision extends javax.swing.JInternalFrame {

     ArrayList<clsEntidadComision> listaComision;  
    clsEntidadComision _objComision;
    
    static ResultSet rs = null;
    DefaultTableModel dtm = new DefaultTableModel();
    
    public FrmConsultaComision() {
        initComponents();
    }

    public void cargarTabla(String busqueda){
          
        listaComision = clsComision.listarComision(busqueda);
        DefaultTableModel dtm = (DefaultTableModel)tblComision.getModel();
        FrmMaster.limpiarTabla(tblComision);
        for(clsEntidadComision objComision : listaComision){
            Object[] fila = new Object[3];
            fila[0] = objComision.getIdPersona();
            fila[1] = objComision.getIdEvento();
            fila[2] = objComision.getTipo();
            
            dtm.addRow(fila);
        }
        tblComision.setModel(dtm);
    }
    
    public void seleccionarTabla(){
        int fila = tblComision.getSelectedRow();
        if (fila==-1){
            JOptionPane.showMessageDialog(null, "Debes seleccionar una fila");
        }else{
            _objComision = listaComision.get(fila);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblComision = new javax.swing.JTable();
        btnComision = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Consultar Comision");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 11, -1, -1));

        btnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/application_add.png"))); // NOI18N
        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 43, -1, -1));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/remove.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 43, -1, -1));

        tblComision.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "idPersona", "idEvento", "Tipo Comision"
            }
        ));
        tblComision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblComisionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblComision);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 672, 110));

        btnComision.setText("Comisiones");
        btnComision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComisionActionPerformed(evt);
            }
        });
        getContentPane().add(btnComision, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        cargarTabla("");
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void tblComisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblComisionMouseClicked
        seleccionarTabla();
    }//GEN-LAST:event_tblComisionMouseClicked

    private void btnComisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComisionActionPerformed
        FrmConsultarComisionEvento comi = new FrmConsultarComisionEvento(_objComision);
        MDIPrincipal.Escritorio1.add(comi);
        comi.show();
    }//GEN-LAST:event_btnComisionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnComision;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblComision;
    // End of variables declaration//GEN-END:variables
}
