/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentacion;
import Negocio.*;
import Presentacion.*;
import Entidad.*;
import Negocio.*;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author BEPIS
 */
public class frmGasto extends javax.swing.JInternalFrame implements IMantenimiento {

    ArrayList<clsEntidadGasto> listaGasto;  
    clsEntidadGasto _objGasto;
    boolean isNuevoActivo;
    
    public frmGasto() {
        initComponents();
        cargarTabla("");
        FrmMaster.BloquearControles(pnlForm);
        FrmMaster.BloquearBotones(pnlForm, "Cancelar");
    }

    @Override
    public void cargarTabla(String busqueda){
        listaGasto = clsGasto.listarGasto(busqueda);
        DefaultTableModel dtm = (DefaultTableModel)tblGasto.getModel();
        FrmMaster.limpiarTabla(tblGasto);
        for(clsEntidadGasto objGasto : listaGasto){
            Object[] fila = new Object[15];
            fila[0] = objGasto.getIdEvento();
            fila[1] = objGasto.getIdGasto();
            fila[2] = objGasto.getConcepto();
            fila[3] = objGasto.getMonto();


            dtm.addRow(fila);
        }
        tblGasto.setModel(dtm);
    }
    
      @Override
    public void seleccionarTabla(){
        int fila = tblGasto.getSelectedRow();
        if (fila==-1){
            JOptionPane.showMessageDialog(null, "Debes seleccionar una fila");
        }else{
            txtEvento.setText(String.valueOf(_objGasto.getIdEvento()));
            txtConcepto.setText(_objGasto.getConcepto());
            txtMonto.setText(String.valueOf(_objGasto.getMonto()));
        }
    }
    
    @Override
    public void guardar(){
        clsEntidadGasto objGasto = new clsEntidadGasto();
        objGasto.setIdEvento(Integer.parseInt(txtEvento.getText()));
        objGasto.setConcepto(txtConcepto.getText());
        objGasto.setMonto(Double.parseDouble(txtMonto.getText()));
        clsGasto.agregarGasto(objGasto);
        cargarTabla("");
    }
    
    @Override
    public void modificar() {
        clsEntidadGasto objGasto = new clsEntidadGasto();
        objGasto.setIdEvento(Integer.parseInt(txtEvento.getText()));
        objGasto.setConcepto(txtConcepto.getText());
        objGasto.setMonto(Double.parseDouble(txtConcepto.getText()));
        clsGasto.modificarGasto(objGasto);
        cargarTabla("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblGasto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        pnlForm = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtConcepto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEvento = new javax.swing.JTextField();
        pnlBotones = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblGasto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idPersona", "idEvento", "Tipo Pago", "Monto"
            }
        ));
        tblGasto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGastoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGasto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 500, 180));

        jLabel1.setText("Mantenimiento de Gasto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 120, -1));

        pnlForm.setBackground(new java.awt.Color(255, 255, 255));
        pnlForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Concepto :");
        pnlForm.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, -1, -1));
        pnlForm.add(txtConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 73, 146, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Monto :");
        pnlForm.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 111, -1, -1));
        pnlForm.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 107, 146, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("ID Evento:");
        pnlForm.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, -1));
        pnlForm.add(txtEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 42, 146, -1));

        pnlBotones.setBackground(new java.awt.Color(255, 255, 255));
        pnlBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, 90, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, 90, -1));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        pnlBotones.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 90, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 90, -1));

        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        pnlBotones.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 144, 90, -1));

        pnlForm.add(pnlBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        getContentPane().add(pnlForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 460, 210));

        jLabel2.setIcon(new javax.swing.ImageIcon("F:\\ProyectoFinal_EventoV4\\Sistema_Eventos\\src\\img\\fondobriseida.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblGastoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGastoMouseClicked
        seleccionarTabla();
    }//GEN-LAST:event_tblGastoMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if(tblGasto.getSelectedRow()>0){
            isNuevoActivo=false;
            FrmMaster.HabilitarControles(pnlForm);
            FrmMaster.BloquearBotones(pnlBotones, "Modificar");
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione un registro!");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(isNuevoActivo){
            guardar();
        }else{
            modificar();
        }
        FrmMaster.BloquearBotones(pnlBotones, "Guardar");
        FrmMaster.LimpiarCampos(pnlForm);
        FrmMaster.BloquearControles(pnlForm);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        isNuevoActivo=true;
        FrmMaster.HabilitarControles(pnlForm);
        FrmMaster.LimpiarCampos(pnlForm);
        FrmMaster.BloquearBotones(pnlBotones, "Nuevo");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        FrmMaster.BloquearBotones(pnlBotones, "Cancelar");
        FrmMaster.LimpiarCampos(pnlForm);
        FrmMaster.BloquearControles(pnlForm);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JTable tblGasto;
    private javax.swing.JTextField txtConcepto;
    private javax.swing.JTextField txtEvento;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
