/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentacion;
import Entidad.*;
import Negocio.*;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author BEPIS
 */
public class frmInscripcion extends javax.swing.JInternalFrame {

    ArrayList<clsEntidadInscripcion> listaInscripcion;  
    clsEntidadInscripcion _objInscripcion;
    boolean isNuevoActivo;
    
    ArrayList<clsEntidadEvento> listaEvento;
    ArrayList<clsEntidadPersona> listaPersona;
    public frmInscripcion() {
        initComponents();
        cargarCombo1();
        cargarCombo();
        cargarTabla("");
        FrmMaster.BloquearControles(pnlForm);
        FrmMaster.BloquearBotones(pnlForm, "Cancelar");
    }

 
    public void cargarTabla(String busqueda){
        listaInscripcion = clsInscripcion.listarInscripcion(busqueda);
        DefaultTableModel dtm = (DefaultTableModel)tblInscripcion.getModel();
        FrmMaster.limpiarTabla(tblInscripcion);
        for(clsEntidadInscripcion objInscripcion : listaInscripcion){
            Object[] fila = new Object[15];
            fila[0] = objInscripcion.getIdPersona();
            fila[1] = objInscripcion.getIdEvento();
            fila[2] = objInscripcion.getTipoPago();
            fila[3] = objInscripcion.getMonto();
            fila[4] = objInscripcion.getFecha();


            dtm.addRow(fila);
        }
        tblInscripcion.setModel(dtm);
    }
    
    public void cargarCombo(){
        listaEvento = clsEvento.listarEventos("");
        DefaultComboBoxModel dtm = new DefaultComboBoxModel();
        dtm.addElement("Seleccione el titulo");
        for(clsEntidadEvento objEvento : listaEvento){
           String evento = objEvento.getTitulo();
            System.out.println(objEvento.getTitulo());
            dtm.addElement(evento);
        }
        cmbTituloEvento.setModel(dtm);
    }
    
    public void cargarCombo1(){
        listaPersona = clsPersona.listarPersonas("");
        DefaultComboBoxModel dtm = new DefaultComboBoxModel();
        dtm.addElement("Seleccione el titulo");
        for(clsEntidadPersona objPersona : listaPersona){
           String persona = objPersona.getNombres();
            System.out.println(objPersona.getNombres());
            dtm.addElement(persona);
        }
        cmbPersona.setModel(dtm);
    }
    
    
    
    
    public void seleccionarTabla(){
        int fila = tblInscripcion.getSelectedRow();
        if (fila==-1){
            JOptionPane.showMessageDialog(null, "Debes seleccionar una fila");
        }else{
            txtTipopago.setText(_objInscripcion.getTipoPago());
            txtMonto.setText(String.valueOf(_objInscripcion.getMonto()));
            txtFecha.setText(String.valueOf(_objInscripcion.getFecha()));
        }
    }
    

    public void guardar(){
        clsEntidadInscripcion objInscripcion = new clsEntidadInscripcion();
        clsEntidadEvento evento = obtenerTituloEventoSeleccionado();
       clsEntidadPersona persona = obtenerPersonaSeleccionado();
       int idEvento = evento.getIdEvento();
       int idPersona = persona.getIdPersona();
       objInscripcion.setIdEvento(idEvento);
       objInscripcion.setIdPersona(idPersona);
        objInscripcion.setTipoPago(txtTipopago.getText());
        objInscripcion.setMonto(Double.parseDouble(txtMonto.getText()));
        objInscripcion.setFecha(txtFecha.getText());
        clsInscripcion.agregarInscripcion(objInscripcion);
       // cargarTabla("");
        
      
    }
    
   
    public void modificar() {
        clsEntidadInscripcion objInscripcion = new clsEntidadInscripcion();
        objInscripcion.setIdPersona(_objInscripcion.getIdPersona());
        objInscripcion.setIdEvento(_objInscripcion.getIdEvento());
        objInscripcion.setTipoPago(txtTipopago.getText());
        objInscripcion.setMonto(Double.parseDouble(txtMonto.getText()));
        clsInscripcion.modificarInscripcion(objInscripcion);
       // cargarTabla("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblInscripcion = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        pnlForm = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTipopago = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbTituloEvento = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtTipoEvento = new javax.swing.JTextField();
        cmbPersona = new javax.swing.JComboBox();
        txtApellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblInscripcion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idPersona", "idEvento", "Tipo Pago", "Monto", "Fecha"
            }
        ));
        tblInscripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInscripcionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInscripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 480, 180));

        jLabel1.setText("Mantenimiento de Inscripcion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 150, -1));

        pnlBotones.setBackground(new java.awt.Color(255, 255, 255));
        pnlBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, 90, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, 90, -1));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        pnlBotones.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 90, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 90, -1));

        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        pnlBotones.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 144, 90, -1));

        getContentPane().add(pnlBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 110, 180));

        pnlForm.setBackground(new java.awt.Color(255, 255, 255));
        pnlForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Persona :");
        pnlForm.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Tipo Evento :");
        pnlForm.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Tipo Pago :");
        pnlForm.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        pnlForm.add(txtTipopago, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 100, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Monto :");
        pnlForm.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        pnlForm.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 100, -1));

        jLabel3.setText("Titulo :");
        pnlForm.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        cmbTituloEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTituloEventoActionPerformed(evt);
            }
        });
        pnlForm.add(cmbTituloEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 100, -1));

        jLabel5.setText("Fecha :");
        pnlForm.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        pnlForm.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 100, -1));
        pnlForm.add(txtTipoEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 100, -1));

        cmbPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPersonaActionPerformed(evt);
            }
        });
        pnlForm.add(cmbPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 100, -1));
        pnlForm.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 100, -1));

        getContentPane().add(pnlForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 360, 210));

        jLabel2.setIcon(new javax.swing.ImageIcon("F:\\ProyectoFinal_EventoV4\\Sistema_Eventos\\src\\img\\fondobriseida.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblInscripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInscripcionMouseClicked
        seleccionarTabla();
    }//GEN-LAST:event_tblInscripcionMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if(tblInscripcion.getSelectedRow()>0){
            isNuevoActivo=false;
            FrmMaster.HabilitarControles(pnlForm);
            FrmMaster.BloquearBotones(pnlBotones, "Modificar");
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione un registro!");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(isNuevoActivo){
            guardar();
        }else{
            modificar();
        }
        FrmMaster.BloquearBotones(pnlBotones, "Guardar");
        FrmMaster.LimpiarCampos(pnlForm);
        FrmMaster.BloquearControles(pnlForm);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        isNuevoActivo=true;
        FrmMaster.HabilitarControles(pnlForm);
        FrmMaster.LimpiarCampos(pnlForm);
        FrmMaster.BloquearBotones(pnlBotones, "Nuevo");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        FrmMaster.BloquearBotones(pnlBotones, "Cancelar");
        FrmMaster.LimpiarCampos(pnlForm);
        FrmMaster.BloquearControles(pnlForm);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void cmbTituloEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTituloEventoActionPerformed
        // TODO add your handling code here:
        if(cmbTituloEvento.getSelectedIndex()>0){
            clsEntidadEvento evento = obtenerTituloEventoSeleccionado();
            int idEvento = evento.getIdEvento();
            String tipo = String.valueOf(evento.getTipo());
            txtTipoEvento.setText(tipo);
            //cargarTabla(idEvente);
        }else{
            FrmMaster.LimpiarCampos(pnlForm);
            //FrmMaster.limpiarTabla(tblKardex);
        }
    }//GEN-LAST:event_cmbTituloEventoActionPerformed

    private void cmbPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPersonaActionPerformed
        // TODO add your handling code here:
        if(cmbPersona.getSelectedIndex()>0){
            clsEntidadPersona persona = obtenerPersonaSeleccionado();
            int idPersona = persona.getIdPersona();
            String apellido = String.valueOf(persona.getApellidos());
            txtApellido.setText(apellido);
            //cargarTabla(idEvente);
        }else{
            FrmMaster.LimpiarCampos(pnlForm);
            //FrmMaster.limpiarTabla(tblKardex);
        }
    }//GEN-LAST:event_cmbPersonaActionPerformed

    private clsEntidadEvento obtenerTituloEventoSeleccionado(){
        int indexCmbArticulo = cmbTituloEvento.getSelectedIndex();
        clsEntidadEvento evento = listaEvento.get(indexCmbArticulo-1);
        return evento;
    }
    
    private clsEntidadPersona obtenerPersonaSeleccionado(){
        int indexCmbPersona = cmbPersona.getSelectedIndex();
        clsEntidadPersona persona = listaPersona.get(indexCmbPersona-1);
        return persona;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox cmbPersona;
    private javax.swing.JComboBox cmbTituloEvento;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JTable tblInscripcion;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtTipoEvento;
    private javax.swing.JTextField txtTipopago;
    // End of variables declaration//GEN-END:variables
}
