/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Presentacion;

import Entidad.*;
import Negocio.*;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class frmPonente extends javax.swing.JInternalFrame implements IMantenimiento{
    ArrayList<clsEntidadPonente> listaPonentes;  
    clsEntidadPonente _objPonente;
    boolean isNuevoActivo;

    
    
    public frmPonente() {
        initComponents();
       cargarTabla("");
        
    }
    
    @Override
    public void cargarTabla(String busqueda){
        listaPonentes = clsPonente.listarPonentes(busqueda);
        DefaultTableModel dtm = (DefaultTableModel)tblPonente.getModel();
        FrmMaster.limpiarTabla(tblPonente);
        for(clsEntidadPonente objPonente : listaPonentes){
            Object[] fila = new Object[6];
            fila[0] = objPonente.getIdPersona();
            fila[1] = objPonente.getNombres();
            fila[2] = objPonente.getApellidos();
            fila[3] = objPonente.getEmail();
            fila[4] = objPonente.getCelular();
            fila[5] = objPonente.getGradoAcademico();
            
            dtm.addRow(fila);
        }
        tblPonente.setModel(dtm);
    }
    
    @Override
    public void seleccionarTabla(){
        int fila = tblPonente.getSelectedRow();
        if (fila==-1){
            JOptionPane.showMessageDialog(null, "Debes seleccionar una fila");
        }else{
            _objPonente = listaPonentes.get(fila);
            txtCelular.setText(_objPonente.getCelular());
            txtGradoAcademico.setText(_objPonente.getGradoAcademico());
            //txtNombre.setText(_objPonente.getNombres());
            //txtApellidos.setText(_objPonente.getApellidos());
        }
    }
    
    @Override
    public void guardar(){
        clsEntidadPonente objPonente = new clsEntidadPonente();
        //objPonente.setNombres(txtNombre.getText());
        //objPonente.setApellidos(txtApellidos.getText());
        objPonente.setCelular(txtCelular.getText());
        objPonente.setGradoAcademico(txtGradoAcademico.getText());
        
        clsPonente.agregarPonente(objPonente);
        cargarTabla("");
    }
    
    @Override
    public void modificar() {
        clsEntidadPonente objPonente = new clsEntidadPonente();
        objPonente.setIdPersona(_objPonente.getIdPersona());
       // objPonente.setNombres(txtNombre.getText());
        //objPonente.setApellidos(txtApellidos.getText());
        objPonente.setCelular(txtCelular.getText());
        objPonente.setGradoAcademico(txtGradoAcademico.getText());
        
        clsPonente.modificarPonente(objPonente);
        cargarTabla("");
    }
  
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPonente = new javax.swing.JTable();
        pnlForm = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtGradoAcademico = new javax.swing.JTextField();
        pnlBotones = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Mantenimiento de Ponente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        tblPonente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "idPersona", "Nombres", "Apellidos", "Email", "Celular", "Grado Academico"
            }
        ));
        tblPonente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPonenteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPonente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 480, 110));

        pnlForm.setBackground(new java.awt.Color(255, 255, 255));
        pnlForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Celular:");
        pnlForm.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        pnlForm.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 170, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Grado Academico:");
        pnlForm.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        pnlForm.add(txtGradoAcademico, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 170, 30));

        getContentPane().add(pnlForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 320, 110));

        pnlBotones.setBackground(new java.awt.Color(255, 255, 255));
        pnlBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevo.setBackground(new java.awt.Color(153, 255, 51));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        pnlBotones.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, -1));

        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/record.png"))); // NOI18N
        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 100, -1));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/page_edit.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 100, -1));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/page_remove.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 100, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/computer_remove.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnlBotones.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 100, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/remove.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 100, -1));

        getContentPane().add(pnlBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 110, 250));

        jLabel2.setIcon(new javax.swing.ImageIcon("F:\\ProyectoFinal_EventoV4\\Sistema_Eventos\\src\\img\\fondobriseida.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPonenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPonenteMouseClicked
        seleccionarTabla();
    }//GEN-LAST:event_tblPonenteMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
      isNuevoActivo=true;
      FrmMaster.HabilitarControles(pnlForm);
      FrmMaster.LimpiarCampos(pnlForm);
      FrmMaster.BloquearBotones(pnlBotones, "Nuevo");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed

        
        if(isNuevoActivo){
            guardar();
        }else{
            modificar();
        }
        FrmMaster.BloquearBotones(pnlBotones, "Guardar");
        FrmMaster.LimpiarCampos(pnlForm);
        FrmMaster.BloquearControles(pnlForm);
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
        
         if(tblPonente.getSelectedRow()>0){
           isNuevoActivo=false;
            FrmMaster.HabilitarControles(pnlForm);
            FrmMaster.BloquearBotones(pnlBotones, "Modificar"); 
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione un registro!");
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
/*
        int r;
        r = JOptionPane.showConfirmDialog(null, "¿Estas seguro de Eliminar el registro?",
            "Pregunta",0);
        if(r==0){
            clsPonente oper = new clsPonente();
            oper.EliminarPonente(Codigo);
            actualizarTabla();
            limpiarCampos();

        }
*/
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        FrmMaster.BloquearBotones(pnlBotones, "Cancelar");
        FrmMaster.LimpiarCampos(pnlForm);
        FrmMaster.BloquearControles(pnlForm);
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JTable tblPonente;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtGradoAcademico;
    // End of variables declaration//GEN-END:variables
}
